<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <AssemblyName>Cocoar.Reflectensions.ExpandableObject</AssemblyName>
    <RootNamespace>Cocoar.Reflectensions</RootNamespace>
    <PackageId>Cocoar.Reflectensions.ExpandableObject</PackageId>
    <Product>Cocoar.Reflectensions.ExpandableObject</Product>
    <PackageDescription>Dynamic expandable objects with dictionary-like behavior for Reflectensions.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoar.Reflectensions\Cocoar.Reflectensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cocoar.Reflectensions.Tests" />
  </ItemGroup>

</Project>
