<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <AssemblyName>Cocoar.Reflectensions.Invoke</AssemblyName>
    <RootNamespace>Cocoar.Reflectensions</RootNamespace>
    <PackageId>Cocoar.Reflectensions.Invoke</PackageId>
    <Product>Cocoar.Reflectensions.Invoke</Product>
    <PackageDescription>Dynamic method invocation helpers with automatic parameter matching and type conversion.</PackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cocoar.Reflectensions\Cocoar.Reflectensions.csproj" />
  </ItemGroup>

</Project>
