<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <AssemblyName>Cocoar.Reflectensions.Common</AssemblyName>
    <RootNamespace>Cocoar.Reflectensions.Common</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Bernhard Windisch</Authors>
    <Company>Cocoar</Company>
    <Description>Common types and interfaces for Reflectensions library.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/cocoar-dev/Reflectensions</PackageProjectUrl>
    <RepositoryUrl>https://github.com/cocoar-dev/Reflectensions</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>Cocoar.Reflectensions.Common</PackageId>
    <Product>Cocoar.Reflectensions.Common</Product>
  </PropertyGroup>

</Project>
